name: Check Blog Files

on:
  push:
    branches-ignore:
      - main  # run on all branches except main

jobs:
  check-blog-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set branch name
        run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Check blog image
        run: |
          IMAGE="public/blogs/images/${BRANCH_NAME}.png"
          if [ ! -f "$IMAGE" ]; then
            echo "❌ $IMAGE not found!"
            exit 1
          else
            echo "✅ $IMAGE exists."
          fi

      - name: Check src/components/Blog/posts.js update
        run: |
          FILE="src/components/Blog/posts.js"

          # If branch has only one commit, check if file exists
          if [ $(git rev-list --count HEAD) -eq 1 ]; then
            if [ -f "$FILE" ]; then
              echo "✅ $FILE exists in first commit"
            else
              echo "❌ $FILE not found in first commit"
              exit 1
            fi
          else
            # Compare last two commits
            PREV_COMMIT=$(git rev-parse HEAD~1)
            if git diff --name-only $PREV_COMMIT HEAD | grep -q "^$FILE"; then
              echo "✅ $FILE was updated"
            else
              echo "❌ $FILE not updated"
              exit 1
            fi
          fi

      - name: Check blog markdown
        run: |
          MD_FILE="public/blogs/${BRANCH_NAME}.md"
          if [ ! -f "$MD_FILE" ]; then
            echo "❌ $MD_FILE not found!"
            exit 1
          else
            echo "✅ $MD_FILE exists."
          fi
