name: Validate Blog Branch

on:
  push:
    branches:
      - "*"

jobs:
  validate-blog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set branch name
        run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Check if issues.md references blog image and markdown
        run: |
          FILE="issues.md"
          IMAGE_PATH="blogs/images/${BRANCH_NAME}.png"
          MARKDOWN_PATH="blogs/${BRANCH_NAME}.md"

          if [ ! -f "$FILE" ]; then
            echo "❌ $FILE not found!"
            exit 1
          fi

          # Check for image reference
          if grep -q "$IMAGE_PATH" "$FILE"; then
            echo "✅ $IMAGE_PATH found in $FILE"
          else
            echo "❌ $IMAGE_PATH missing in $FILE"
            exit 1
          fi

          # Check for markdown reference
          if grep -q "$MARKDOWN_PATH" "$FILE"; then
            echo "✅ $MARKDOWN_PATH found in $FILE"
          else
            echo "❌ $MARKDOWN_PATH missing in $FILE"
            exit 1
          fi

      - name: Check if src/components/Blog was updated
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "^src/components/Blog"; then
            echo "✅ src/components/Blog was updated"
          else
            echo "❌ src/components/Blog not updated"
            exit 1
          fi
