name: Check Blog Files

on:
  push:
    branches-ignore:
      - main  # run on all branches except main

jobs:
  check-blog-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set branch name
        run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Check blog image
        run: |
          IMAGE="public/blogs/images/${BRANCH_NAME}.png"
          if [ ! -f "$IMAGE" ]; then
            echo "❌ $IMAGE not found!"
            exit 1
          else
            echo "✅ $IMAGE exists."
          fi

      - name: Check src/components/Blog/posts.js update
        run: |
          FILE="src/components/Blog/posts.js"

          # Determine previous commit
          PREV_COMMIT=${{ github.event.before }}
          if [ "$PREV_COMMIT" == "0000000000000000000000000000000000000000" ] || [ -z "$PREV_COMMIT" ]; then
            PREV_COMMIT="HEAD~1"
          fi

          # Check if file changed
          if git diff --name-only $PREV_COMMIT ${{ github.sha }} | grep -q "^$FILE"; then
            echo "✅ $FILE was updated"
          else
            echo "❌ $FILE not updated"
            exit 1
          fi

      - name: Check blog markdown
        run: |
          MD_FILE="public/blogs/${BRANCH_NAME}.md"
          if [ ! -f "$MD_FILE" ]; then
            echo "❌ $MD_FILE not found!"
            exit 1
          else
            echo "✅ $MD_FILE exists."
          fi
